Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import twint
import nest_asyncio
nest_asyncio.apply()
c = twint.Config()
c.Search = 'Universitas Trunojoyo Madura'
c.Pandas = True
c.Limit = 50
twint.run.Search(c)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn [5], line 1[0m
[1;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mtwint[39;00m
[0;32m      2[0m [38;5;28;01mimport[39;00m [38;5;21;01mnest_asyncio[39;00m
[0;32m      3[0m nest_asyncio[38;5;241m.[39mapply()

File [1;32mD:\Document\jupyter-book\mynewbook\twint\twint\__init__.py:14[0m
[0;32m     12[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mconfig[39;00m [38;5;28;01mimport[39;00m Config
[0;32m     13[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01m__version__[39;00m [38;5;28;01mimport[39;00m __version__
[1;32m---> 14[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m [38;5;28;01mimport[39;00m run
[0;32m     16[0m _levels [38;5;241m=[39m {
[0;32m     17[0m     [38;5;124m'[39m[38;5;124minfo[39m[38;5;124m'[39m: logging[38;5;241m.[39mINFO,
[0;32m     18[0m     [38;5;124m'[39m[38;5;124mdebug[39m[38;5;124m'[39m: logging[38;5;241m.[39mDEBUG
[0;32m     19[0m }
[0;32m     21[0m _level [38;5;241m=[39m os[38;5;241m.[39mgetenv([38;5;124m'[39m[38;5;124mTWINT_DEBUG[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124minfo[39m[38;5;124m'[39m)

File [1;32mD:\Document\jupyter-book\mynewbook\twint\twint\run.py:4[0m
[0;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01msys[39;00m[38;5;241m,[39m [38;5;21;01mos[39;00m[38;5;241m,[39m [38;5;21;01mdatetime[39;00m
[0;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01masyncio[39;00m [38;5;28;01mimport[39;00m get_event_loop, [38;5;167;01mTimeoutError[39;00m, ensure_future, new_event_loop, set_event_loop
[1;32m----> 4[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m [38;5;28;01mimport[39;00m datelock, feed, get, output, verbose, storage
[0;32m      5[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mtoken[39;00m [38;5;28;01mimport[39;00m TokenExpiryException
[0;32m      6[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m [38;5;28;01mimport[39;00m token

File [1;32mD:\Document\jupyter-book\mynewbook\twint\twint\datelock.py:5[0m
[0;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mdatetime[39;00m
[0;32m      3[0m [38;5;28;01mimport[39;00m [38;5;21;01mlogging[39;00m [38;5;28;01mas[39;00m [38;5;21;01mlogme[39;00m
[1;32m----> 5[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mtweet[39;00m [38;5;28;01mimport[39;00m utc_to_local
[0;32m      8[0m [38;5;28;01mclass[39;00m [38;5;21;01mDatelock[39;00m:
[0;32m      9[0m     until [38;5;241m=[39m [38;5;28;01mNone[39;00m

File [1;32mD:\Document\jupyter-book\mynewbook\twint\twint\tweet.py:5[0m
[0;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mdatetime[39;00m [38;5;28;01mimport[39;00m datetime, timezone
[0;32m      4[0m [38;5;28;01mimport[39;00m [38;5;21;01mlogging[39;00m [38;5;28;01mas[39;00m [38;5;21;01mlogme[39;00m
[1;32m----> 5[0m [38;5;28;01mfrom[39;00m [38;5;21;01mgoogletransx[39;00m [38;5;28;01mimport[39;00m Translator
[0;32m      6[0m [38;5;66;03m# ref. [39;00m
[0;32m      7[0m [38;5;66;03m# - https://github.com/x0rzkov/py-googletrans#basic-usage[39;00m
[0;32m      8[0m translator [38;5;241m=[39m Translator()

[1;31mModuleNotFoundError[0m: No module named 'googletransx'
ModuleNotFoundError: No module named 'googletransx'

